In [1]:
import pandas as pd 
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('chefmozcuisine.csv', sep=',',skiprows=1, names=['placeID','cuisine'])

In [3]:
df.head()

   placeID         cuisine
0   135110         Spanish
1   135109         Italian
2   135107  Latin_American
3   135106         Mexican
4   135105       Fast_Food

In [4]:
place_titles = pd.read_csv('geoplaces2.csv')
place_titles.head()

,placeID,latitude,longitude,the_geom_meter,name,address,city,state,country,fax,...,alcohol,smoking_area,dress_code,accessibility,price,url,Rambience,franchise,area,other_services
0,134999,18.915421,-99.184871,0101000020957F000088568DE356715AC138C0A525FC46...,Kiku Cuernavaca,Revolucion,Cuernavaca,Morelos,Mexico,?,...,No_Alcohol_Served,none,informal,no_accessibility,medium,kikucuernavaca.com.mx,familiar,f,closed,none
1,132825,22.147392,-100.983092,0101000020957F00001AD016568C4858C1243261274BA5...,puesto de tacos,esquina santos degollado y leon guzman,s.l.p.,s.l.p.,mexico,?,...,No_Alcohol_Served,none,informal,completely,low,?,familiar,f,open,none
2,135106,22.149709,-100.976093,0101000020957F0000649D6F21634858C119AE9BF528A3...,El Rinc�n de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,?,...,Wine-Beer,only at bar,informal,partially,medium,?,familiar,f,open,none
3,132667,23.752697,-99.163359,0101000020957F00005D67BCDDED8157C1222A2DC8D84D...,little pizza Emilio Portes Gil,calle emilio portes gil,victoria,tamaulipas,?,?,...,No_Alcohol_Served,none,informal,completely,low,?,familiar,t,closed,none
4,132613,23.752903,-99.165076,0101000020957F00008EBA2D06DC8157C194E03B7B504E...,carnitas_mata,lic. Emilio portes gil,victoria,Tamaulipas,Mexico,?,...,No_Alcohol_Served,permitted,informal,completely,medium,?,familiar,t,closed,none

In [5]:
df = pd.merge(df, place_titles, on='placeID')
df.head()

,placeID,cuisine,latitude,longitude,the_geom_meter,name,address,city,state,country,...,alcohol,smoking_area,dress_code,accessibility,price,url,Rambience,franchise,area,other_services
0,135109,Italian,18.921785,-99.235350,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,...,Wine-Beer,not permitted,informal,no_accessibility,medium,?,quiet,f,closed,Internet
1,135106,Mexican,22.149709,-100.976093,0101000020957F0000649D6F21634858C119AE9BF528A3...,El Rinc�n de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,...,Wine-Beer,only at bar,informal,partially,medium,?,familiar,f,open,none
2,135104,Mexican,23.752982,-99.168434,0101000020957F00007CDF5EAFC58157C1645743B23E4F...,vips,?,?,?,?,...,Full_Bar,not permitted,informal,completely,medium,?,familiar,t,closed,variety
3,135088,Cafeteria,18.876011,-99.219890,0101000020957F0000E14AD4DBC7765AC1F7B33C85B153...,Cafeteria cenidet,Interior Internado Palmira SN,Cuernavaca,Morelos,Mexico,...,No_Alcohol_Served,not permitted,informal,no_accessibility,low,www.cenidet.edu.mx,quiet,f,closed,none
4,135086,Burgers,22.141421,-101.013955,0101000020957F0000FA1A0E5A9B4858C17C884C4173AE...,Mcdonalds Parque Tangamanga,Lateral Salvador Nava Martinez 3145,San Luis Potosi,SLP,Mexico,...,No_Alcohol_Served,not permitted,informal,no_accessibility,medium,?,familiar,t,closed,none

In [6]:
df.columns

Index(['placeID', 'cuisine', 'latitude', 'longitude', 'the_geom_meter', 'name',
       'address', 'city', 'state', 'country', 'fax', 'zip', 'alcohol',
       'smoking_area', 'dress_code', 'accessibility', 'price', 'url',
       'Rambience', 'franchise', 'area', 'other_services'],
      dtype='object')

In [7]:
dfofPlaceCuisinePrice=df[['placeID','cuisine','price']]

In [8]:
dfofPlaceCuisinePrice.head()

   placeID    cuisine   price
0   135109    Italian  medium
1   135106    Mexican  medium
2   135104    Mexican  medium
3   135088  Cafeteria     low
4   135086    Burgers  medium

In [10]:
from sklearn import preprocessing

In [11]:
le = preprocessing.LabelEncoder()
le1 = preprocessing.LabelEncoder()
dfofPlaceCuisinePrice['cuisine'] = le.fit_transform(dfofPlaceCuisinePrice.cuisine.values)

In [12]:
dfofPlaceCuisinePrice['price'] = le1.fit_transform(dfofPlaceCuisinePrice.price.values)

In [13]:
dfofPlaceCuisinePrice.head(10)

   placeID  cuisine  price
0   135109       15      2
1   135106       18      2
2   135104       18      2
3   135088        8      1
4   135086        6      2
5   135086       12      2
6   135085       12      2
7   135079        9      0
8   135075       21      2
9   135074       10      0

In [14]:
dfofPlaceCuisinePrice

     placeID  cuisine  price
0     135109       15      2
1     135106       18      2
2     135104       18      2
3     135088        8      1
4     135086        6      2
..       ...      ...    ...
107   132594       18      1
108   132584       18      2
109   132583        0      1
110   132572        8      1
111   132560       20      1

[112 rows x 3 columns]

In [15]:
list(le1.inverse_transform([0, 1, 2]))

['high', 'low', 'medium']

In [16]:
maxval=dfofPlaceCuisinePrice['cuisine'].idxmax()
maxval

87

In [17]:
maxcuisine=dfofPlaceCuisinePrice['cuisine'][maxval]

In [18]:
listofdata=[]
for im in range(maxcuisine):
    listofdata.append(im)

In [19]:
listofdata

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [20]:
list(le.inverse_transform(listofdata))

['American',
 'Armenian',
 'Bakery',
 'Bar',
 'Bar_Pub_Brewery',
 'Breakfast-Brunch',
 'Burgers',
 'Cafe-Coffee_Shop',
 'Cafeteria',
 'Chinese',
 'Contemporary',
 'Family',
 'Fast_Food',
 'Game',
 'International',
 'Italian',
 'Japanese',
 'Mediterranean',
 'Mexican',
 'Pizzeria',
 'Regional',
 'Seafood']

In [25]:
opof=df[df['cuisine']=='Bar']

In [26]:
opof

,placeID,cuisine,latitude,longitude,the_geom_meter,name,address,city,state,country,...,alcohol,smoking_area,dress_code,accessibility,price,url,Rambience,franchise,area,other_services
10,135073,Bar,22.147175,-100.974269,0101000020957F0000D010A853D34858C116A1EA51CAA2...,Restaurante Bar El Gallinero,Pascual M. Hernandez 210 Centro,San Luis Potosi,SLP,Mexico,...,Wine-Beer,section,informal,no_accessibility,high,?,familiar,f,closed,none
13,135071,Bar,22.126375,-100.910926,0101000020957F0000E3A742BFC14D58C1F4E529A7F391...,Restaurante la Cantina,De La Estrella 2005 Estrella de Oriente,San Luis Potosi,SLP,Mexico,...,Full_Bar,section,informal,no_accessibility,medium,?,familiar,f,closed,none
15,135069,Bar,22.140129,-100.944872,0101000020957F000038E5D546B74A58C18FD29AD0D29A...,Abondance Restaurante Bar,Industrias 908 Valle Dorado,San Luis Potosi,SLP,Mexico,...,Wine-Beer,none,informal,no_accessibility,low,?,familiar,f,closed,none
17,135059,Bar,22.145108,-100.989547,0101000020957F000005810F19B84858C136805B2745A7...,Restaurant Bar Hacienda los Martinez,Santos Degollado 745 los Alamitos,San Luis Potosi,SLP,Mexico,...,Wine-Beer,section,informal,no_accessibility,medium,?,familiar,f,closed,none
19,135057,Bar,22.145992,-100.955118,0101000020957F000095669021894958C182C9C10E669D...,El Herradero Restaurante and Bar,Costado Sur Central Camionera Km 2,San Luis Potosi,SLP,Mexico,...,Wine-Beer,section,informal,no_accessibility,medium,?,familiar,f,closed,none
25,135052,Bar,22.150981,-100.977412,0101000020957F0000B72147F1274858C189A406ED75A3...,La Cantina Restaurante,Ignacio Aldama 300 Centro,San Luis Potosi,SLP,Mexico,...,Full_Bar,none,informal,no_accessibility,high,lacantinaslp.com,familiar,f,closed,none
28,135048,Bar,22.142017,-100.999246,0101000020957F00008032636EEC4858C16CDF265038AA...,Restaurante Bar Fu-hao,Jesus Goytortua 390 Tangamanga,San Luis Potosi,SLP,Mexico,...,Wine-Beer,none,informal,no_accessibility,high,?,familiar,f,closed,none
34,135041,Bar,22.151060,-100.977659,0101000020957F0000D2002719234858C1CC7A9FC186A3...,Luna Cafe,Francisco I. Madero 215,San Luis Potosi,SLP,Mexico,...,Wine-Beer,none,informal,no_accessibility,medium,lunacafe.com.mx,familiar,f,closed,none
45,135026,Bar,22.148665,-101.001273,0101000020957F0000C75F8790D94758C1FF8BCA0567AA...,la Cantina,Capitan Caldera No. 420 Tequisqueapan,San Luis Potosi,SLP,Mexico,...,Full_Bar,none,informal,no_accessibility,high,lacantinaslp.com,familiar,f,closed,none
49,135019,Bar,18.875011,-99.159422,0101000020957F0000B49B2E5C6E785AC12F9D58435241...,Restaurant Bar Coty y Pablo,Paseo de Las Fuentes 24 Pedregal de Las Fuentes,Jiutepec,Morelos,Mexico,...,No_Alcohol_Served,none,informal,completely,low,?,familiar,f,closed,none
53,134983,Bar,18.948657,-99.235361,0101000020957F0000DEF36F4FC76A5AC162B083D9A054...,Restaurant and Bar and Clothesline Carlos N Ch...,Domingo 10 711 El Empleado,Cuernavaca,Morelos,Mexico,...,Full_Bar,section,informal,no_accessibility,high,carlosandcharlies.com,familiar,f,closed,none
62,132937,Bar,22.150019,-100.979920,0101000020957F0000F9F19DDC3B4858C191B265A83BA4...,rockabilly,agustin de iturbide,san luis potosi,san luis potosi,mexico,...,Full_Bar,section,informal,completely,low,?,quiet,f,closed,variety
65,132921,Bar,22.150305,-100.989134,0101000020957F00006376BB64EF4758C1013687E5D7A6...,crudalia,?,?,?,?,...,Wine-Beer,section,casual,completely,low,?,quiet,f,open,none